### ISSUE TITLE
Best way to move a hotbar button in its entirety?

### ISSUE THREAD

**Issue by heyyitsdaniel** [MidoriKami/HUDUnlimited#1]
I'm pretty confused by all this stuff:

https://i.imgur.com/idtNrEW.png

What's the best way to simply move a single hotbar button and all of its elements?

**Comment by MidoriKami** [comment]
A `Component` is a combination of several elements, you want to find the component that represents the hotbar button that you want to move.

![image](https://github.com/user-attachments/assets/9c166d65-cebc-475c-808e-9c7266d4168f)

Unfortunately a button can only be clicked on if it is within the `Addon` that it belongs to, so if you move the button outside this area it won't be clickable anymore.
![image](https://github.com/user-attachments/assets/1b1a933b-7d25-488b-84fd-15fcee239a10)

There are some tricks you might be able to use however, to scale up the hotbar in the Vanilla HUD Layout, and then use HUDUnlimited to then scale the parts back down, so the moved element is still within the `Addon`.

![image](https://github.com/user-attachments/assets/3d0b3345-e0eb-46af-b87c-20b085491676)
