### ISSUE TITLE
Node Recycling

### ISSUE THREAD

**Issue by WesBosch** [MidoriKami/HUDUnlimited#2]
Overrides on certain addons will sometimes reassign themselves to different nodes as nodes are recycled by the addon.

Currently, this is known to happen on the _HudLayoutScreen addon

![image](https://github.com/user-attachments/assets/56b44fb1-4064-42d8-b8a1-a5269c41fec7)
![image](https://github.com/user-attachments/assets/1f1baf04-9d91-4d5b-bed2-83ccf2ba0737)

**Comment by MidoriKami** [comment]
In several places in the game where you might have a variable number of "something", the game likes to pre-allocate all the possible nodes that you might need, and it simply "fills", "moves", or "hides" nodes that aren't in use.

This means that for any highly dynamic element or list of elements, HUDUnlimited will not be able to consistently modify the elements that you want.

Another such example of this are Name Plates, the game recycles these often, and quite quickly, so if you wish to edit one Name Plate, you'll have to edit **all** Name Plates.
